apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: myrepo
  namespace: default
spec:
  gitImplementation: go-git
  interval: 30s
  ref:
    branch: master
  timeout: 5m
  url: https://github.com/ljakimczuk/myrepo
