apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: myrepo
  namespace: default
spec:
  force: false
  interval: 30s
  path: ./
  prune: true
  serviceAccountName: automation
  sourceRef:
    kind: GitRepository
    name: myrepo
    namespace: default
  suspend: false
